/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.sql.direct;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;

@SpringBootApplication
public class App {
    private final EntityManagerFactory entityManagerFactory;

    private final EntityManager entityManager;

    private final JdbcTemplate jdbcTemplate;

    public App(EntityManagerFactory entityManagerFactory,
               EntityManager entityManager,
               JdbcTemplate jdbcTemplate) {
        this.entityManagerFactory = entityManagerFactory;
        this.entityManager = entityManager;
        this.jdbcTemplate = jdbcTemplate;
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Bean
    public CommandLineRunner demo() {
        return (args -> {
            System.out.println("Start");

            System.out.printf("entityManagerFactory is null: %b %n", entityManagerFactory == null);
            System.out.printf("entityManager is null: %b %n", entityManager == null);
            System.out.printf("jdbcTemplate is null: %b %n", jdbcTemplate == null);

            test1();
            test2();
            test3();
            test4();
        });
    }

    private void test1() {
        System.out.println("==>test1");
        var query = entityManager.createNativeQuery("""
                select * from test_autos
                """);

        query.getResultList().forEach(System.out::println);
    }

    private void test2() {
        System.out.println("==>test2");
        var query = entityManager.createNativeQuery("""
                select * from test_autos
                """, TestAuto.class);

        query.getResultList().forEach(System.out::println);
    }

    private void test3() {
        System.out.println("==>test3");
        var sql = """
                select * from test_autos
                """;
        jdbcTemplate.query(sql, new TestAutoRowMapper())
                .forEach(System.out::println);
    }

    private void test4() {
        System.out.println("==>test4");
        var query = entityManager.createNativeQuery("""
                select * from test_autos limit :limit
                """, TestAuto.class);
        query.setParameter("limit", 5);

        var sqlAsString = query.unwrap(org.hibernate.query.Query.class).getQueryString();
        System.out.printf("Query: %s%n", sqlAsString);

        query.getResultList().forEach(System.out::println);
    }

}
