/*
 * Copyright (c) 2018. Yuriy Stul
 */

package com.stulsoft.pspring.mysql.application

import java.util.function.Consumer

import org.springframework.beans.factory.InitializingBean
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.CommandLineRunner
import org.springframework.boot.autoconfigure.SpringBootApplication

import scala.concurrent.{Await, Future}
import scala.concurrent.duration._
/**
  * @author Yuriy Stul
  */
@SpringBootApplication(scanBasePackages = Array("com.stulsoft.pspring.mysql"))
class Application @Autowired()(private val userRepository:UserRepository) extends CommandLineRunner  with InitializingBean{
  // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
//  @Autowired
//  private var userRepository: UserRepository = _


  override def run(args: String*): Unit = {
    println("==>run")
    import scala.concurrent.ExecutionContext.Implicits.global
    val user = new User()
    user.email = "email 5"
    user.name = "the name 5"

    println(s"Saving $user")
    val result = userRepository.save(user)
    println(s"Saved $result")

    println("Print all users:")
    def printConsumer = new Consumer[User] {
      override def accept(user: User): Unit = {
        println(user)
      }
    }
    val futures = (1 to 3).map(_ =>{
      Future{
        userRepository.findAll().forEach(printConsumer)
      }
    })

    futures.foreach(f => Await.result(f, 5.seconds))

    println("<==run")
  }

  override def afterPropertiesSet(): Unit = {}
}

