/*
 * Copyright (c) 2018. Yuriy Stul
 */

package com.stulsoft.pspring.mysql.application

import com.stulsoft.pspring.mysql.data.{User, UserRepository, UserSRepository}
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.CommandLineRunner
import org.springframework.boot.autoconfigure.SpringBootApplication

/**
  * @author Yuriy Stul
  */
@SpringBootApplication
class Application extends CommandLineRunner {
  // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private var userRepository: UserRepository = _

  @Autowired
  private var userSRepository:UserSRepository=_

  override def run(args: String*): Unit = {
    val user = new User()
    user.setEmail("email")
    user.setName("the name")

    userRepository.save(user)
  }
}
