/*
 * Copyright (c) 2018. Yuriy Stul
 */

package com.stulsoft.pspring.mysql.application

import org.springframework.beans.factory.InitializingBean
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.CommandLineRunner
import org.springframework.boot.autoconfigure.SpringBootApplication

/**
  * @author Yuriy Stul
  */
@SpringBootApplication(scanBasePackages = Array("com.stulsoft.pspring.mysql"))
class Application @Autowired()(private val userRepository:UserRepository) extends CommandLineRunner  with InitializingBean{
  // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
//  @Autowired
//  private var userRepository: UserRepository = _


  override def run(args: String*): Unit = {
    println("==>run")
    val user = new User()
    user.email = "email 5"
    user.name = "the name 5"

    println(s"Saving $user")
    val result = userRepository.save(user)
    println(s"Saved $result")
    println("<==run")
  }

  override def afterPropertiesSet(): Unit = {}
}

